api_name: bak_basic
derived_fields:
  list_date_dt:
    description: 日期类型的list_date
    format: '%Y%m%d'
    source: list_date
    type: date
  trade_date_dt:
    description: 日期类型的trade_date
    format: '%Y%m%d'
    source: trade_date
    type: date
description: 备用基础数据
enabled: false
name: bak_basic
output:
  primary_key:
  - trade_date
  - ts_code
  sort_by:
  - trade_date
pagination:
  enabled: true
  mode: date_range
  window_size_days: 365
parameters:
  trade_date:
    default: '20231201'
    description: 交易日期 YYYYMMDD
    required: false
    type: string
  ts_code:
    description: 股票代码
    required: false
    type: string
permissions:
  min_points: 5000
  query_limit: 7000
  rate_limit: 60
request:
  extra_path: ''
  method: POST
  timeout: 30
