api_name: namechange
derived_fields:
  ann_date_dt:
    description: 日期类型的ann_date
    format: '%Y%m%d'
    source: ann_date
    type: date
  end_date_dt:
    description: 日期类型的end_date
    format: '%Y%m%d'
    source: end_date
    type: date
  start_date_dt:
    description: 日期类型的start_date
    format: '%Y%m%d'
    source: start_date
    type: date
description: 股票曾用名
name: namechange
output:
  primary_key:
  - ts_code
  - ann_date
  - start_date
  sort_by:
  - ann_date
pagination:
  enabled: false
parameters:
  ann_date:
    description: 公告日期 YYYYMMDD
    required: false
    type: string
  end_date:
    description: 公告结束日期 YYYYMMDD
    required: false
    type: string
  start_date:
    description: 公告开始日期 YYYYMMDD
    required: false
    type: string
  ts_code:
    description: TS代码
    required: false
    type: string
permissions:
  min_points: 0
  query_limit: 10000
  rate_limit: 60
request:
  extra_path: ''
  method: POST
  timeout: 30
