api_name: report_rc
derived_fields:
  report_date_dt:
    description: 日期类型的report_date
    format: '%Y%m%d'
    source: report_date
    type: date
  create_time_dt:
    description: 日期时间类型的create_time
    format: '%Y-%m-%d %H:%M:%S'
    source: create_time
    type: datetime
description: 卖方盈利预测数据
name: report_rc
output:
  primary_key:
  - ts_code
  - name
  - report_date
  - report_title
  - report_type
  - classify
  - org_name
  - author_name
  - quarter
  - op_rt
  - op_pr
  - tp
  - np
  - eps
  - pe
  - rd
  - roe
  - ev_ebitda
  - rating
  - max_price
  - min_price
  - imp_dg
  - create_time
  sort_by:
  - report_date
pagination:
  enabled: true
  mode: reverse_date_range
  window_size_days: 1
  empty_threshold_days: 90 
parameters:
  end_date:
    description: 报告结束日期 YYYYMMDD
    required: false
    type: string
  report_date:
    description: 报告日期 YYYYMMDD
    required: false
    type: string
  start_date:
    description: 报告开始日期 YYYYMMDD
    required: false
    type: string
  ts_code:
    description: 股票代码
    required: false
    type: string
permissions:
  min_points: 8000
  query_limit: 3000
  rate_limit: 60
request:
  extra_path: ''
  method: POST
  timeout: 30

fields:
  ts_code: string
  name: string
  report_date: string
  report_title: string
  report_type: string
  classify: string
  org_name: string
  author_name: string
  quarter: string
  op_rt: float
  op_pr: float
  tp: float
  np: float
  eps: float
  pe: float
  rd: float
  roe: float
  ev_ebitda: float
  rating: string
  max_price: float
  min_price: float
  imp_dg: string
  create_time: string
