api_name: repurchase
derived_fields:
  ann_date_dt:
    description: 日期类型的ann_date
    format: '%Y%m%d'
    source: ann_date
    type: date
  end_date_dt:
    description: 日期类型的end_date
    format: '%Y%m%d'
    source: end_date
    type: date
  exp_date_dt:
    description: 日期类型的exp_date
    format: '%Y%m%d'
    source: exp_date
    type: date
description: 股票回购
name: repurchase
output:
  primary_key:
  - ts_code
  - ann_date
  sort_by:
  - ann_date
pagination:
  date_field: ann_date
  enabled: true
  mode: date_range
  window_size_days: 365
parameters:
  ann_date:
    description: 公告日期 YYYYMMDD
    required: false
    type: string
  end_date:
    description: 公告结束日期 YYYYMMDD
    required: false
    type: string
  start_date:
    description: 公告开始日期 YYYYMMDD
    required: false
    type: string
permissions:
  min_points: 600
  query_limit: 2000
  rate_limit: 60
request:
  extra_path: ''
  method: POST
  timeout: 30
