api_name: stk_premarket
derived_fields:
  trade_date_dt:
    description: 日期类型的trade_date
    format: '%Y%m%d'
    source: trade_date
    type: date
description: 每日开盘前获取当日股票的股本情况
name: stk_premarket
output:
  primary_key:
  - ts_code
  - trade_date
  sort_by:
  - trade_date
  - ts_code
pagination:
  enabled: true
  mode: date_range
  window_size_days: 365
parameters:
  end_date:
    description: 结束日期
    required: false
    type: string
  start_date:
    description: 开始日期
    required: false
    type: string
  trade_date:
    description: 交易日期(YYYYMMDD格式)
    required: false
    type: string
  ts_code:
    description: 股票代码
    required: false
    type: string
permissions:
  min_points: 0
  query_limit: 8000
  rate_limit: 120
request:
  extra_path: ''
  method: POST
  timeout: 30
