api_name: stock_company
derived_fields:
  setup_date_dt:
    description: 日期类型的setup_date
    format: '%Y%m%d'
    source: setup_date
    type: date
description: 上市公司基本信息
name: stock_company
output:
  primary_key:
  - ts_code
  sort_by:
  - ts_code
pagination:
  default_limit: 5000
  enabled: true
  limit_key: limit
  mode: offset
  offset_key: offset
parameters:
  exchange:
    description: 交易所代码 SSE上交所 SZSE深交所 BSE北交所
    required: false
    type: string
  ts_code:
    description: 股票代码
    required: false
    type: string
permissions:
  min_points: 120
  query_limit: 10000
  rate_limit: 60
request:
  extra_path: ''
  method: POST
  timeout: 30
